import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Common/Header/Header";
import Sidebar from "@/app/components/Common/Sidebar/Sidebar";
// import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Header />
        {/* <Sidebar /> */}
        <main className="mt-[2.5vw]">{children}</main>
      </body>
    </html>
  );
}
